"""
DFP TakeoffPro — License Key System
------------------------------------
LICENSING IS CURRENTLY DISABLED (OPEN MODE).
The app runs without a key.

To enable licensing when you are ready to sell:
  1. Set  LICENSING_ENABLED = True  below.
  2. Give customers keys generated by keygen.py.
  3. On first launch they are prompted to enter their key.

Key format:  DFPTP-XXXXX-XXXXX-XXXXX-XXXXX
             5 groups × 5 chars, uppercase alphanumeric (base-32)
"""

import os, sys, json, hmac, hashlib, base64, struct, uuid, platform
from datetime import date, timedelta

# ── Config ────────────────────────────────────────────────────────────────────

# Set to True when you want to enforce license checks (e.g. when selling)
LICENSING_ENABLED = False

# Secret used to sign/verify keys.  NEVER share this.
# Change this to any long random string before distributing.
_SECRET = b"DFP_TP_K3Y_S1GN3R_v1_2024_Change_Me!"

# Where activation is stored on the customer's machine
_ACTIVATION_FILE = os.path.join(
    os.environ.get("APPDATA", os.path.expanduser("~")),
    "DFP TakeoffPro", "activation.json"
)

# Epoch for expiry encoding (days since this date)
_EPOCH = date(2024, 1, 1)


# ── Machine ID ────────────────────────────────────────────────────────────────

def get_machine_id() -> str:
    """Stable ID derived from MAC address + computer name."""
    mac  = str(uuid.getnode())
    name = platform.node()
    return hashlib.sha256(f"{mac}:{name}".encode()).hexdigest()[:16]


# ── Key generation (run keygen.py, not this directly) ────────────────────────

def generate_key(expiry: date, seats: int = 1) -> str:
    """
    Create a signed license key.
    expiry  — date the key expires
    seats   — number of activations allowed (currently informational)
    """
    days    = (expiry - _EPOCH).days
    payload = struct.pack(">IB", days, max(1, seats))          # 5 bytes
    sig     = hmac.new(_SECRET, payload, hashlib.sha256).digest()[:10]  # 10 bytes
    raw     = sig + payload                                     # 15 bytes
    encoded = base64.b32encode(raw).decode().rstrip("=")        # 24 chars
    groups  = [encoded[i:i+5] for i in range(0, 24, 5)]        # 5 × ~5
    # Pad last group if short (base32 of 15 bytes = 24 chars exactly, no padding needed)
    return "DFPTP-" + "-".join(groups)


# ── Key validation ────────────────────────────────────────────────────────────

def _decode_key(key: str):
    """Returns (expiry: date, seats: int) or raises ValueError."""
    clean = key.upper().replace("-", "")
    if clean.startswith("DFPTP"):
        clean = clean[5:]
    if len(clean) != 24:
        raise ValueError("Wrong key length")
    pad = (8 - len(clean) % 8) % 8
    raw = base64.b32decode(clean + "=" * pad)
    if len(raw) != 15:
        raise ValueError("Decode failed")
    sig      = raw[:10]
    payload  = raw[10:]
    expected = hmac.new(_SECRET, payload, hashlib.sha256).digest()[:10]
    if not hmac.compare_digest(sig, expected):
        raise ValueError("Invalid signature")
    days, seats = struct.unpack(">IB", payload)
    expiry = _EPOCH + timedelta(days=days)
    return expiry, seats


def validate_key(key: str) -> tuple:
    """Returns (ok: bool, message: str, expiry: date|None, seats: int)."""
    try:
        expiry, seats = _decode_key(key)
        if expiry < date.today():
            return False, f"Key expired {expiry}", expiry, seats
        return True, f"Valid until {expiry}", expiry, seats
    except Exception as e:
        return False, str(e), None, 0


# ── Activation (local machine binding) ───────────────────────────────────────

def activate(key: str) -> tuple:
    """Bind this key to this machine. Returns (ok, message)."""
    ok, msg, expiry, seats = validate_key(key)
    if not ok:
        return False, msg
    record = {
        "key":        key.upper(),
        "machine_id": get_machine_id(),
        "expiry":     str(expiry),
        "seats":      seats,
    }
    try:
        os.makedirs(os.path.dirname(_ACTIVATION_FILE), exist_ok=True)
        with open(_ACTIVATION_FILE, "w") as f:
            json.dump(record, f, indent=2)
        return True, f"Activated! License valid until {expiry}."
    except Exception as e:
        return False, f"Could not save activation: {e}"


def check_activation() -> tuple:
    """
    Returns (licensed: bool, message: str).
    If LICENSING_ENABLED is False, always returns (True, "Open mode").
    """
    if not LICENSING_ENABLED:
        return True, "Open mode"

    if not os.path.exists(_ACTIVATION_FILE):
        return False, "No license found. Please enter your license key."

    try:
        with open(_ACTIVATION_FILE) as f:
            data = json.load(f)
    except Exception:
        return False, "Activation file is corrupted. Please re-activate."

    # Machine binding check
    if data.get("machine_id") != get_machine_id():
        return False, (
            "This license is registered to a different computer.\n"
            "Please contact Defense Fire Protection for assistance."
        )

    # Re-validate the key itself (detects tampering)
    ok, msg, expiry, _ = validate_key(data.get("key", ""))
    if not ok:
        return False, msg

    return True, f"Licensed to this computer until {expiry}"


def deactivate():
    """Remove local activation (e.g. to move to a new machine)."""
    if os.path.exists(_ACTIVATION_FILE):
        os.remove(_ACTIVATION_FILE)
